# This file was generated by GoReleaser. DO NOT EDIT.
cask "stash" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "b4bb1a5afc5b1016c1a6a51ff5201b713e06b240a12f20c795ea7b0ceaa8fd30"
      url "https://github.com/lightning-rider-999/go-stash/releases/download/v#{version}/stash_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b27b6ad6c2161ab6d0bf4ba3f8e96595c0b6c86289c0ccf61916f59c26de6480"
      url "https://github.com/lightning-rider-999/go-stash/releases/download/v#{version}/stash_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "55017f4f8268a767fb0366b327306478cee1b8af960caf7dceceff4d8a2bf761"
      url "https://github.com/lightning-rider-999/go-stash/releases/download/v#{version}/stash_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7acb894d7e013189e56b07238cc0509e1bf6fec248daf54eecb2a9d0a64cde34"
      url "https://github.com/lightning-rider-999/go-stash/releases/download/v#{version}/stash_#{version}_linux_arm64.tar.gz"
    end
  end

  name "stash"
  desc "Go client/library & CLI for the stash GraphQL API"
  homepage "https://github.com/lightning-rider-999/go-stash"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stash"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/stash"]
    end
  end

  # No zap stanza required

end
