# This file was generated by GoReleaser. DO NOT EDIT.
cask "stash" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "8da53cfb5c338eb0fe3b81fac558d210c093c5cf3e651f40639e7e8b7a05afce"
      url "https://github.com/lightning-rider-999/go-stash/releases/download/v#{version}/stash_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "267726e90bd868f79333547704a047387ffe358d3a54ecfdb3be7dc9a8979ef7"
      url "https://github.com/lightning-rider-999/go-stash/releases/download/v#{version}/stash_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5b17a133347b888e5d867bbb0343c011038b1d94895d576ee14eff2c3c99dda7"
      url "https://github.com/lightning-rider-999/go-stash/releases/download/v#{version}/stash_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4b6102692938dd366c42669920b83c1f65ca8e977bb65ce0452f2a0d7080b303"
      url "https://github.com/lightning-rider-999/go-stash/releases/download/v#{version}/stash_#{version}_linux_arm64.tar.gz"
    end
  end

  name "stash"
  desc "Go client/library & CLI for the stash GraphQL API"
  homepage "https://github.com/lightning-rider-999/go-stash"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stash"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/stash"]
    end
  end

  # No zap stanza required

end
