# This file was generated by GoReleaser. DO NOT EDIT.
cask "stashbox" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "1246780550564a2e14ac40178b6437a635fe037eb3d07afe88c61a8aade41536"
      url "https://github.com/lightning-rider-999/go-stashbox/releases/download/v#{version}/stashbox_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bdc11cd3430c30c4f0b3ee4cb2d786dcf4d34e1935a85c575101f2f2e5a602df"
      url "https://github.com/lightning-rider-999/go-stashbox/releases/download/v#{version}/stashbox_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bec7fcd25d7bcbac7cfdaede2420fc55bff949179e6a50e28d9b1954d58c7902"
      url "https://github.com/lightning-rider-999/go-stashbox/releases/download/v#{version}/stashbox_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7b5ac3ae8a5e58bea010b8eeacd5fe953ce510159e89184bb910ee0da6d59b9a"
      url "https://github.com/lightning-rider-999/go-stashbox/releases/download/v#{version}/stashbox_#{version}_linux_arm64.tar.gz"
    end
  end

  name "stashbox"
  desc "Go client/library & CLI for stash-box's GraphQL API (StashDB and any stash-box instance)"
  homepage "https://github.com/lightning-rider-999/go-stashbox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stashbox"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/stashbox"]
    end
  end

  # No zap stanza required

end
