# This file was generated by GoReleaser. DO NOT EDIT.
cask "stashbox" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "bbb2f0a57eb105b79603be14ac7d3f6a2f108d3949ecb9a19596f4097fcec93b"
      url "https://github.com/lightning-rider-999/go-stashbox/releases/download/v#{version}/stashbox_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d0791f5c619c64c32c1a0ccdeb5c455b861864a805c98694dc33950babbad2a1"
      url "https://github.com/lightning-rider-999/go-stashbox/releases/download/v#{version}/stashbox_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6ec4fbe2790268337c3f8426743e19f54ceb3f26978bd205b4a74837f54eb046"
      url "https://github.com/lightning-rider-999/go-stashbox/releases/download/v#{version}/stashbox_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a93931420ed5b821b0f8b9b3738db6c68e099560f12fd8433c4f5274bf264d56"
      url "https://github.com/lightning-rider-999/go-stashbox/releases/download/v#{version}/stashbox_#{version}_linux_arm64.tar.gz"
    end
  end

  name "stashbox"
  desc "Go client/library & CLI for stash-box's GraphQL API (StashDB and any stash-box instance)"
  homepage "https://github.com/lightning-rider-999/go-stashbox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stashbox"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/stashbox"]
    end
  end

  # No zap stanza required

end
